### ISSUE TITLE
No possibility to be notified at the time users get the BeReal notification

### ISSUE THREAD

**Issue by ArtrenH** [notmarek/BeFake#11]
Does anyone have any idea how that works in the App?

**Comment by notmarek** [comment]
> Does anyone have any idea how that works in the App?

I think they use https://firebase.google.com/docs/cloud-messaging as the rest of the app uses a lot of firebase too.

**Comment by JacobKfromIRC** [comment]
Hi, I made a program that does this, independently of BeFake. Instead of interacting with BeReal directly, it uses a third party API service that relays the time information, so it probably wouldn't be very useful for implementing the feature in BeFake, but maybe @ArtrenH will find it useful anyway. If using the program I made, one will probably want to modify it if they are not running Trisquel (the OS I use).

link to the program: https://codeberg.org/JacobK/unofficial-notifier-for-BeReal
