### ISSUE TITLE
Unable to post with error: 'old-post'

### ISSUE THREAD

**Issue by tandpfun** [notmarek/BeFake#61]
Hi! I get this error when trying to post a BeReal. It's a late BeReal, but if I set "is_late" to True or False, I get the same error. I'm not exactly sure what's causing it:
``` js
{'error': 'Bad Request', 'statusCode': 400, 'message': 'Bad Request', 'errorKey': 'old-post', 'fields': None, 'timestamp': '2023-03-27T02:58:30.760Z', 'requestId': '[I removed this]'}
```

**Comment by VxlerieUwU** [comment]
Huh, I'll try to post a late BeReal tomorrow.

**Comment by tandpfun** [comment]
Did ya reproduce the issue?

I haven't figured out how to MITM proxy BeReal cus they have some sort of thing that's preventing it from working. How did you do it?

**Comment by VxlerieUwU** [comment]
> Did ya reproduce the issue?
> 
> I haven't figured out how to MITM proxy BeReal cus they have some sort of thing that's preventing it from working. How did you do it?

I've been quite inactive this week because of some exams, you need to install some kind of certificate unpinner, for example if you have [lsposed](https://modules.lsposed.org/module/io.github.tehcneko.sslunpinning) (this works with latest BeReal) or using [frida](https://httptoolkit.com/blog/frida-certificate-pinning/) (Haven't tried this) on Android.
HTTP Toolkit is the easiest to use, especially if you have a rooted phone. You also need a basic safetynet attestation to log into BeReal now. If you are using an iPhone, I will not be able to help you.

**Comment by VxlerieUwU** [comment]
@tandpfun can you reproduce the issue on 2d28e3e95db1bd1aecd95157c23af34f3ad200eb?

**Comment by tandpfun** [comment]
Nope, it works on that version! Thank you :)

**Comment by VxlerieUwU** [comment]
There was some things undone with the implementation of the Location object, probably screwed everything up when you didn't specify one at runtime
